[bugfix] Straighten out command-line error handling
els0r/goProbe pull request #106
Opened 2023-04-11 09:33 UTC by fako1024

What I've done:

- Replaced all manual error handling / output in the `cobra` entrypoint function to simply return the error to the caller
- Handle any error from that function in `Execute()`, using "our" logger with its `Fatalf()` method
- Initialize our logger directly in `init()` instead of via `cobra` (to ensure it's already initialized if the error occurs before `cobra` can call the initializer)

@els0r For now I've kept this a draft because there are two open questions IMHO:

- [ ] Should we maybe add a special formatter for the command line tool(s)? Right now we throw a message like this:
```
ts=2023-04-11T11:23:51.976+02:00 level=fatal msg="Error running query: failed to prepare query: failed to parse query type: Unknown attribute name: 'protod'" version=872abf81
```
TBH I don't think that someone running a CLI expects a "logger" style response but rather something like:
```
Error running query: failed to prepare query: failed to parse query type: Unknown attribute name: 'protod'
```
- [ ] The same changes should probably be applied to `global-query` (because the same problem about not notifying errors happens there as indicated in #43 )

What's your take on those open questions?

Closes #104

2023-04-11 16:16 UTC, els0r requested changes
Changes requested because we need the:

* plain/CLI logging handler (I prefer plain because it's closer to what the logger does or doesn't do)
* use the logger only in `Execute`
* `if err` stuff because it'll create merge conflicts with #43 that are tedious to fix

2023-04-11 16:16 UTC, els0r commented on cmd/goQuery/commands/root.go
> +		if err := listInterfaces(cmdLineParams.DBPath, cmdLineParams.External); err != nil {
Can we agree to leave each other alone when it comes to the `err; if err` controversy? Unless the OCD trigger is above 9000 an we need to settle the debate and do it consistently across the code base.

2023-04-11 16:16 UTC, els0r commented on cmd/goQuery/commands/root.go
> +		logging.Logger().Fatalf("Error running query: %s", err)
With the recent changes in https://github.com/els0r/goProbe/pull/108, we'd just instantiate a "plain" CLI logger_ before the if and then call that one.

2023-04-11 16:16 UTC, els0r commented on cmd/goQuery/commands/root.go
> +		if err := listInterfaces(cmdLineParams.DBPath, cmdLineParams.External); err != nil {
Would also appreciate it if it isn't touched until https://github.com/els0r/goProbe/issues/43 is done

2023-04-11 16:16 UTC, els0r commented on cmd/goQuery/commands/root.go
> +		if err = jsoniter.NewEncoder(stmt.Output).Encode(res); err != nil {
Same here

2023-04-11 16:16 UTC, els0r commented on cmd/goQuery/commands/root.go
> +		if err = json.Unmarshal(argumentsJSON, &queryArgs); err != nil {
Same here

2023-04-11 16:16 UTC, els0r commented on cmd/goQuery/commands/root.go
> +	if err = stmt.Print(ctx, result); err != nil {
Same here

2023-04-14 20:26 UTC, els0r approved these changes
Good to go from my end. Feel free to merge when available.

2023-04-14 20:26 UTC, els0r commented on cmd/goQuery/commands/root.go
> +	cliLogger, err = logging.New(logging.LevelError, logging.EncodingPlain,
Plain logger is now taken for the error from the entrypoint. From my end, this is fine. I'll do the global-query one inside #43 .

2023-04-15 10:20 UTC, fako1024 commented
> Good to go from my end. Feel free to merge when available.

Awesome, thanks a lot for taking care of the CLI stuff! I just gave it a quick spin, seems to cover all cases now and error "results" look very readable now. :muscle:

2023-04-15 10:20 UTC, merged