[feature] Add volume metrics to goProbe and introduce iface label
els0r/goProbe pull request #237
Opened 2023-10-05 21:56 UTC by els0r

### Background

This commit add three new metrics to goProbe:

* `goprobe_capture_bytes_received_total`
* `goprobe_capture_bytes_sent_total`
* `goprobe_capture_flows_total`

These are calculated and supplied to prometheus only upon aggregation, which is in line with the approach chosen for the other capture metrics during `status()` calls.

### Major Changes

Let's unleash cardinality onto the metrics backends. Metrics of the `capture` subsystem are now vectors with exactly one label: `iface`.

The decision was made to discern better

* on which interface errors/drops occured
* how large the flow maps were
* how much traffic volume was observed per interface

The latter two providing a more detailed understanding of bursts or interfaces over which many sessions are routed

2023-10-05 22:00 UTC, els0r commented
@fako1024 : this will expand our drill-down capabilities before a global rollout. Have fun

2023-10-06 09:24 UTC, fako1024 requested changes
@els0r Let's have a chat about this. All these things we did before and I removed them to avoid unnecessary overhead. Yes, this happens only during rotation, but it happens while the capture is blocked and the local buffer is filling, so each operation you're doing will increase the required buffer depth and may increase the number of drops.
Yes, knowing the global traffic is cool, but I don't think we should gather it manually from the flows this way. Isn't there any way we can retrieve it from the status or elsewhere (e.g. from the interface socket - I'd be happy to provide something via `slimcap` if we can in turn avoid the additional overhead here)? If not then I'd at least minimize the effort / overhead by just adding a new counter next to `nProcessed` (`nBytesProcessed` or similar) and increment that one in the `addToFlowLog()` by the readily available `pktSize` value. That way it may be in the processing flow again, but it's _really_ just _one_ simple variable increment without any additional logic / complexity / overhead (and after all, inbound / outbound won't give you any insight on global level anyway and you don't have those for the packets either).

2023-10-06 09:25 UTC, fako1024 commented
Tests are broken due to naming conflict: `panic: a previously registered descriptor with the same fully-qualified name as Desc{fqName: "goprobe_capture_bytes_received_total", help: "Number of bytes send", constLabels: {}, variableLabels: [{iface <nil>}]} has different label names or a different help string`

2023-10-06 21:34 UTC, els0r commented
> @els0r Let's have a chat about this. All these things we did before and I removed them to avoid unnecessary overhead. Yes, this happens only during rotation, but it happens while the capture is blocked and the local buffer is filling, so each operation you're doing will increase the required buffer depth and may increase the number of drops. Yes, knowing the global traffic is cool, but I don't think we should gather it manually from the flows this way. Isn't there any way we can retrieve it from the status or elsewhere (e.g. from the interface socket - I'd be happy to provide something via `slimcap` if we can in turn avoid the additional overhead here)? If not then I'd at least minimize the effort / overhead by just adding a new counter next to `nProcessed` (`nBytesProcessed` or similar) and increment that one in the `addToFlowLog()` by the readily available `pktSize` value. That way it may be in the processing flow again, but it's _really_ just _one_ simple variable increment without any additional logic / complexity / overhead (and after all, inbound / outbound won't give you any insight on global level anyway and you don't have those for the packets either).

I'd beg to differ. It feels like we are in counting nanoseconds territory here. The code is set up to do the least amount of work possible to obtain and store those counters. What's effectively happening:

- 1 call to reset counters
- n*4 arithmetic operations (simple add), where n is the number of flows in map
- 3 calls to prometheus to update the counters

Considering the complexity of the flow map aggregation, I am not convinced that this introduces any significant performance hit. If it does, we should talk about what's acceptable and what isn't. And then go with the aggregation in `nBytesProcessed`.

2023-10-06 21:39 UTC, els0r commented
Just a side note on Prometheus: https://github.com/prometheus/client_golang/issues/677

2023-10-06 21:50 UTC, els0r commented
> Tests are broken due to naming conflict: `panic: a previously registered descriptor with the same fully-qualified name as Desc{fqName: "goprobe_capture_bytes_received_total", help: "Number of bytes send", constLabels: {}, variableLabels: [{iface <nil>}]} has different label names or a different help string`

The joys of copy-pasta. Thanks!

I need to find out a way to develop this in Docker. It's pretty limiting not running these tests prior to push.

2023-10-06 23:57 UTC, els0r commented on examples/config/goprobe-example-config-devcontainer.yaml
> +    promisc: false
Promiscuous doesn't work inside docker

2023-10-09 16:16 UTC, fako1024 approved these changes
As discussed, go for it!

2023-10-09 16:16 UTC, fako1024 commented on pkg/capture/flow.go
> +		f.totals.BytesRcvd += v.bytesRcvd
Please move inside the condition below (no need to count if zero packets are observed)

2023-10-09 16:16 UTC, fako1024 commented on pkg/capture/flow.go
> +	totals types.Counters
Remove in favor of local return variable in `transferAndAggregate`

2023-10-09 16:16 UTC, fako1024 commented on pkg/capture/capture.go
> +	promPacketsProcessed.WithLabelValues(c.iface).Add(float64(c.stats.Processed))
As discussed: Do some goroutine / label magic.

2023-10-09 16:16 UTC, fako1024 commented on pkg/types/keyval.go
> +func (c Counters) Reset() {
Not needed if local return is used.

2023-10-09 19:00 UTC, merged