39 simplify the table printer
els0r/goProbe pull request #42
Opened 2023-01-25 14:21 UTC by els0r

# Summary

Provides a `results.Result` structure that is returned to a printing routine. This data structure itself allows aggregation of its rows in case results from different systems should be aggregated.

It's the first step towards a distributed-query tool.

As preparation, it also adds support for `ctx` to the `query.Execute` and `query.Print` (new) methods, allowing callers to cancel any ongoing query operations. So far that was only possible via killing the command line tool. Thus, a critical flaw of the API is removed, where queries would continue even though the request was cancelled.

2023-01-25 16:15 UTC, fako1024 requested changes
Nice one, some neat cleanup going on there! Just some very minor feedback, otherwise lgtm!

2023-01-25 16:15 UTC, fako1024 commented on pkg/goDB/keyval.go
> -			uint16(uint16(k.Dport[0])<<8 | uint16(k.Dport[1])),
The outer uint16() should be unnecessary (doesn't your linter make mimimi about that?)

2023-01-25 16:15 UTC, fako1024 commented on cmd/goQuery/commands/help.go
> -  [-e txt|csv|json|influxdb] [-d <db-path>] [-f <timestamp>] [-l <timestamp>]
The horror! ;-)

2023-01-25 16:15 UTC, fako1024 commented on pkg/goDB/DBWorkManager.go
> +			numEntries := int(len(blocks[BytesRcvdColIdx]) / 8)
This will create conflicts with #37 (needs careful cross-checking to avoid unnoticed issues)...

2023-01-25 16:15 UTC, fako1024 commented
Ran a few queries, seems to yield the same results as before from what I gather... :+1:

2023-01-25 16:44 UTC, els0r commented on pkg/goDB/Query.go
> +		q.queryAttributeIndices = append(q.queryAttributeIndices, colIdx)
Freaked out every time I saw it :D

2023-01-25 16:46 UTC, els0r commented on pkg/goDB/DBWorkManager.go
> +					w.logger.Warnf("[D %s; B %d] Failed to read %s.gpf: %s", dir, tstamp, columnFileNames[colIdx], err.Error())
Got it. Will factor this in for the logging refactor. `goQuery` will then use a global logger that logs to `os.Stderr` by default unless someone really wants to log to a file.

Fully agree that having to guess whether something went wrong vs. just seeing it, is suboptimal.

2023-01-30 17:24 UTC, fako1024 approved these changes

2023-01-30 19:43 UTC, merged